### ISSUE TITLE
Arduino sketch 

### ISSUE THREAD

**Issue by WhoIsMrSentry** [dmt-labs/modular-biped#51]
Hi, I have a problem, I am using arduino pro micro as a card (atmel ATmega32u4 to load code from computer is selected as arduino leonardo)

I downloaded the arduino sketch, but normally it writes serialprint, but I tried it at 115200 baud setting (the value specified in the sketch) on my computer, but it did not write anything to the serial monitor.

**Comment by danic85** [comment]
Have you enabled the debug flag in the config.h file?


________________________________
From: Emir HAMURCU ***@***.***>
Sent: Tuesday, August 22, 2023 9:19:00 AM
To: dmt-labs/modular-biped ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dmt-labs/modular-biped] Arduino sketch (Issue #51)


Hi, I have a problem, I am using arduino pro micro as a card (atmel32u4 to load code from computer is selected as arduino leonardo)

I downloaded the arduino sketch, but normally it writes serialprint, but I tried it at 115200 baud setting (the value specified in the sketch) on my computer, but it did not write anything to the serial monitor.

**Comment by SentryCoderDev** [comment]
I guess you didn't activate

**Comment by danic85** [comment]
It's disabled by default to improve performance and avoid any unnecessary communication from the Arduino to the pi (or other SoC). There are also feature specific debug flags that can be enabled in some cases.

**Comment by SentryCoderDev** [comment]
Ok, i did as you said and it worked thank you for your reply
